
services:
###> doctrine/doctrine-bundle ###
  mhbc-front:
    container_name: mhbc-front
    image: "local/mhbc-front:latest"
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      APP_KEY: 'base64:VDjFZGfLFfJHSENXBNdOF8Lv1xrIY3tCCZis0lIN0h0='
      APP_NAME: "MHBC"
      DB_PORT: "5432"
      DB_DATABASE: "mhbc-db"
      DB_USERNAME: "-app"
      DB_PASSWORD: "-!ChangeMe!"
      DB_CONNECTION: "pgsql"
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_SECURE: "false"

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: "mhbc-db"
      # You should definitely change the password in production
      POSTGRES_PASSWORD: "-!ChangeMe!"
      POSTGRES_USER: "-app"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
